### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by BigfootN** [varemenos/atom-toolbar-almighty#12]
Hello,

After having successfully installed the tool-bar package and this package, I'm unable to make it work.

Your package interested me because it could override the default entries (which I checked in the settings). So, just to test it I copied/pasted the example in your README.md, where it said how the file should look like, in the same path that was indicated (~/.atom/custom_entries.js). But it didn't change a thing. I even tried to restart atom but without any success.

Atom: 1.4.0-beta3
OS: Archlinux

Thank you very much in advance for any response :)

**Comment by AidanNichol** [comment]
I too had a problem similar to yours using v1.3.2 on OSX. Mine turned out to be a syntax error in my configuration js file. Here is what I learnt along the way to solving my problem.
1. If you make any change to the configuration of the package or to your custom file then you need at least to select `View/Reload` from the menu.
2. Selecting `View/Developer/Toggle Developer Tools` first will let you see the javascript console and any error messages. Most likely you'll see an error in `util.coffee` around line 9
3. I cut and pasted the example and that worked for me. You say that you've done that already so you're probably looking at at error where it isn't finding the file. You should have your file in the `~/.atom` directory tree and in the configuration of this package MUST be specified it relative to ~/.atom e.g. simply `custom_entries.js`. Any attempt to specify the full path would fail.

Hope this helps

**Comment by varemenos** [comment]
Sorry guys I'm currently away serving my mandatory military service. @ScriptorNY do you still have this issue? Did @AidanNichol's comment fix your issue?

**Comment by BigfootN** [comment]
Hello,

I'm really sorry for my late response, but I was quite busy for the past time, and thank you very much for yours.

Concerning the error, in the developer console, I haven't seen related to `util.coffee`.
So, after entering the file's name it seems to have responded, but there are still the default entries (Override default entries is checked), even though `custom_entries.js` only contains:

```
module.exports = [
]
```

Here is what I have:

![toolbar](https://cloud.githubusercontent.com/assets/1183923/13031058/9c89906c-d2be-11e5-9b2c-376ad6e06ecc.png)

Thank you very much in advance

**Comment by varemenos** [comment]
So I've finally got a little bit of time to deal with this issue.

Now that I've re-read your comment I see that you have the option "override the defaults" enabled but you don't provide anything in your settings. Unless I'm misunderstanding something what you are describing basically means you don't need the toolbar (since you don't need the defaults and you don't provide anything in the custom entries), and it's puzzling me on whether this is actually a bug and whether I should spend time "fixing" it (my time is really really limited right now).

I will leave this open for now and see whether what I understand is what you described above. I will fix it of course but it will have low priority, hope you don't mind.

**Comment by varemenos** [comment]
It's been almost a year, I don't think this issue is something I'd be willing to fix.
This fits the use case of https://atom.io/packages/flex-tool-bar instead of tool-bar-almighty.

Sorry for the inconvenience, hope you understand my reasoning.
