### ISSUE TITLE
[Feature Request] Option to toggle each tool-bar entry on/off.

### ISSUE THREAD

**Issue by Splike** [varemenos/atom-toolbar-almighty#19]
In the settings page, I'd like to see a check box  next to each default tool-bar entry. This should let me easily disable entries I don't want displayed.

**Comment by varemenos** [comment]
Hi, thank you for taking an interest in this package.
Please allow me to spend a few days thinking about whether it makes sense to implement this issue.

I've been absent for a long time due to personal reasons and I need to check the codecase and see whether this feature is easy to implement and whether it will make it harder to maintain.

**Comment by Splike** [comment]
Sure, thanks for taking your time to consider my request.
