### ISSUE TITLE
Open terminal doesn't show up with term3

### ISSUE THREAD

**Issue by acgetchell** [varemenos/atom-toolbar-almighty#9]
![screen shot 2016-01-01 at 5 06 17 pm](https://cloud.githubusercontent.com/assets/434849/12072809/ffb3d512-b0a9-11e5-8198-00df35fdc52f.png)

**Comment by varemenos** [comment]
I've removed term-related entries since November, they've been blocking a feature I think is far more useful (custom entries) and made the structure simpler.

Relevant commits: 
https://github.com/varemenos/atom-toolbar-almighty/commit/f11de5bacf37a366f27bdad34ed4ff5cfde23878
https://github.com/varemenos/atom-toolbar-almighty/commit/a01080fa5eb0537cd457d4cd3ad47834dc25da5f

If you are interested in adding term3 back please use the [custom entries](https://github.com/varemenos/atom-toolbar-almighty#custom-entries) feature and add the following:

``` js
{
  type: 'button',
  tooltip: 'Term3 Split Down',
  dependency: 'term3',
  callback: 'term3:open-split-down',
  icon: 'terminal'
}
```

Really sorry for this but it had to be done. I'm closing this issue, if you need further assistance or if you think there is still something relevant to this issue that we have to discuss, let me know so I can reopen it.

**Comment by acgetchell** [comment]
Ok, sure. Perhaps the documentation should reflect this?

**Comment by varemenos** [comment]
Yes, I will go ahead and update the documentation and I will also add a link to this issue for people that are looking for term2/3
